### ISSUE TITLE
Add reverse lookup data source

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-dns#31]
Add a `dns_reverse_lookup` data source potentially using https://golang.org/pkg/net/#LookupAddr

**Comment by apparentlymart** [comment]
For consistency with existing names I think it'd be called `dns_ptr_record_set`, though we may want to provide some additional UX help here by accepting an IP address in its usual form rather than requiring it to be converted into the `.in-addr.arpa` or `.ip6.arpa` form.

```hcl
data "dns_ptr_record_set" "consistent_example" {
  # Support "host" for consistency with the other data sources
  host = "1.2.1.10.in-addr.arpa"
}

data "dns_ptr_record_set" "convenient_example" {
  # Also support "ip_address" that accepts either an IPv4 or IPv6 in its canonical form
  ip_address = "10.1.2.1"
}
```

Supporting that first form above would actually require some extra work because `LookupAddr` does not, as far as I know, accept the DNS form. So it would be reasonable to start with the latter `ip_address` form only and see if a need for the `host` form emerges, since I expect usage of that will be more marginal.
