### ISSUE TITLE
Make signed read requests optional

### ISSUE THREAD

**Issue by rifelpet** [terraform-providers/terraform-provider-dns#47]
Our terraform setup is as follows:
* All users may plan locally before checking in changes to a git repo
* Applies may only occur in a CI environment controlled by the ops team

With the 1.0.0 DNS provider we were able to default the provider's `key_secret` to a dummy value which wasn't used during plans, and then set the real secret in the CI environment via an environment variable for when update and deletes are actually performed. This way we didn't need to check the secret into the git repo and users do not have write access to our BIND server. For the record, we have a similar setup with the AWS provider -- users have read access to (almost) all resources but only the CI environment has update/delete access, enforced via IAM permissions.

It appears that the signing of read requests introduced in 2.0.0 broke this workflow. We would now need to give all users write access to BIND in order for them to run plans.

Would it be possible to make the signing of read requests optional, exposed as a provider config option? Alternatively, what would be a feasible solution for this that mimics our existing workflow?

### Terraform Version
```
Terraform v0.11.7
+ provider.dns v2.0.0
```

### Affected Resource(s)
- all resources

### Terraform Configuration Files
```hcl
provider "dns" {
  version = "~> 2.0.0"
  update {
    server        = "1.2.3.4"
    key_name      = "ci_key."
    key_algorithm = "hmac-md5"
    key_secret    = "${var.dns_key}"
  }
}
variable "dns_key" {
  default = "MY_KEY"
}
resource "dns_a_record_set" "this" {
  zone      = "mydomain.com."
  name      = "rifelpet"
  addresses = ["192.168.1.1"]
  ttl       = 300
}
```

### Debug Output
https://gist.github.com/rifelpet/36dcd7c7f0b2949db23f498a93a38845

### Expected Behavior
The DNS record should be queried without the secret_key and the plan should succeed

### Actual Behavior
The plan failed due to a DNS query error:
```
* dns_a_record_set.this: dns_a_record_set.this: Error querying DNS record: illegal base64 data at input byte 2
```

### Steps to Reproduce
1. Alter the config file above to create a DNS record on a bind server, setting  the`TF_VAR_dns_key` env var to the RNDC secret.
2. Run a `terraform plan` with the `dns_key` variable set to its default value.

**Comment by apparentlymart** [comment]
Hi @rifelpet! Sorry for the unexpected collision with your workflow here.

In general Terraform expects that `plan` and `apply` will be run with the same credentials, across all providers.

The exception here, of course, is when `terraform plan` is being run just for development purposes (what we call a "speculative plan") where the plan is immediately discarded and never applied. In that case, users often _do_ employ anonymous access or read-only credentials.

The usual pattern for this is to provide credentials to Terraform via environment variables rather than configuration. In general we always recommend using out-of-band mechanisms to provide credentials where possible, and provide these configuration-based mechanisms only for unusual situations where e.g. the same provider is used multiple times in the configuration with different credentials.

I notice that the documentation for this provider in particular doesn't describe the environment variable equivalents for each of its options, which is a documentation bug. To implement the pattern I described for this provider I think the relevant variables are `DNS_UPDATE_KEYNAME`, `DNS_UPDATE_KEYALGORITHM` and `DNS_UPDATE_KEYSECRET`.

If you omit the `key_name`, `key_algorithm`, and `key_secret` arguments altogether and then set those environment variables when creating and applying plans "for real" then it should work fine without those variables set in a development environment when creating a speculative plan.

If you'd like to retain the existing technique of passing the key in using a Terraform variable then an alternative would be to also set `key_name` from a variable and leave both variables set to the empty string (e.g. via `default = ""`) when creating a speculative plan, which should achieve the same effect because the provider activates signed requests only if `key_name` is non-empty.

**Comment by rifelpet** [comment]
@apparentlymart Thanks for the quick response! I just tested out your suggestion of leaving out the key_* provider config parameters and instead setting those env vars in the CI environment and that worked perfectly.

I'm sure others would appreciate a docs update but it looks like our existing workflow will continue to work for 2.0.0.

Thanks again.
