### ISSUE TITLE
NS records addition to this provider.

### ISSUE THREAD

**Issue by anuiq** [terraform-providers/terraform-provider-dns#5]
We are currently using the nsupdate command to add NS records to our DNS servers. We generate a zone in Route53 and the NS records associated with that zone is what we want to add to our servers. We were trying to find a provider that can help with that. This provider adds A, Cname and ptr records but not NS (correct me if I am wrong-- very new to Terraform)? Are you guys working on NS records ?

I tried to replicate what has been done to add A records however my terraform apply gives me 

* dns_ns_record_set.testingNS: 1 error(s) occurred:

* dns_ns_record_set.testingNS: dns_ns_record_set.testingNS: Error querying DNS record: 3*

The read, create and update functions that I have added look like the following 

READ && UPDATE 

```func resourceDnsNSRecordSetRead(d *schema.ResourceData, meta interface{}) error {

	if meta != nil {

		rec_name := d.Get("name").(string)
		rec_zone := d.Get("zone").(string)

		if rec_zone != dns.Fqdn(rec_zone) {
			return fmt.Errorf("Error reading DNS record: \"zone\" should be an FQDN")
		}

		rec_fqdn := fmt.Sprintf("%s.%s", rec_name, rec_zone)

		c := meta.(*DNSClient).c
		srv_addr := meta.(*DNSClient).srv_addr

		msg := new(dns.Msg)
		msg.SetQuestion(rec_fqdn, dns.TypeNS)

		r, _, err := c.Exchange(msg, srv_addr)
		if err != nil {
			return fmt.Errorf("Error querying DNS record: %s", err)
		}
		if r.Rcode != dns.RcodeSuccess {
			return fmt.Errorf("Error querying DNS record: %v", r.Rcode)
		}

		nameservers := schema.NewSet(schema.HashString, nil)
		for _, record := range r.Answer {
			nameserver, err := getNSVal(record)
			if err != nil {
				return fmt.Errorf("Error querying DNS record: %s", err)
			}
			nameservers.Add(nameserver)
		}
		if !nameservers.Equal(d.Get("nameservers")) {
			d.SetId("")
			return fmt.Errorf("DNS record differs")
		}
		return nil
	} else {
		return fmt.Errorf("update server is not set")
	}
}

func resourceDnsNSRecordSetUpdate(d *schema.ResourceData, meta interface{}) error {

	if meta != nil {

		rec_name := d.Get("name").(string)
		rec_zone := d.Get("zone").(string)
		ttl := d.Get("ttl").(int)

		if rec_zone != dns.Fqdn(rec_zone) {
			return fmt.Errorf("Error updating DNS record: \"zone\" should be an FQDN")
		}

		rec_fqdn := fmt.Sprintf("%s.%s", rec_name, rec_zone)

		c := meta.(*DNSClient).c
		srv_addr := meta.(*DNSClient).srv_addr
		keyname := meta.(*DNSClient).keyname
		keyalgo := meta.(*DNSClient).keyalgo

		msg := new(dns.Msg)

		msg.SetUpdate(rec_zone)

		if d.HasChange("nameservers") {
			o, n := d.GetChange("nameservers")
			os := o.(*schema.Set)
			ns := n.(*schema.Set)
			remove := os.Difference(ns).List()
			add := ns.Difference(os).List()

			// Loop through all the old nameservers and remove them
			for _, nameserver := range remove {
				rr_remove, _ := dns.NewRR(fmt.Sprintf("%s %d A %s", rec_fqdn, ttl, nameserver.(string)))
				msg.Remove([]dns.RR{rr_remove})
			}
			// Loop through all the new nameservers and insert them
			for _, nameserver := range add {
				rr_insert, _ := dns.NewRR(fmt.Sprintf("%s %d A %s", rec_fqdn, ttl, nameserver.(string)))
				msg.Insert([]dns.RR{rr_insert})
			}

			if keyname != "" {
				msg.SetTsig(keyname, keyalgo, 300, time.Now().Unix())
			}

			r, _, err := c.Exchange(msg, srv_addr)
			if err != nil {
				d.SetId("")
				return fmt.Errorf("Error updating DNS record: %s", err)
			}
			if r.Rcode != dns.RcodeSuccess {
				d.SetId("")
				return fmt.Errorf("Error updating DNS record: %v", r.Rcode)
			}

			nameservers := ns
			d.Set("nameservers", nameservers)
		}

		return resourceDnsNSRecordSetRead(d, meta)
	} else {
		return fmt.Errorf("update server is not set")
	}
}

```
CREATE 

```
func resourceDnsNSRecordSetCreate(d *schema.ResourceData, meta interface{}) error {

	rec_name := d.Get("name").(string)
	rec_zone := d.Get("zone").(string)

	if rec_zone != dns.Fqdn(rec_zone) {
		return fmt.Errorf("Error creating DNS record: \"zone\" should be an FQDN")
	}

	rec_fqdn := fmt.Sprintf("%s.%s", rec_name, rec_zone)

	d.SetId(rec_fqdn)

	return resourceDnsARecordSetUpdate(d, meta)
}
```

The terraform plan I am trying to apply looks like this 

```provider "dns" {
  update {
    server        = "aaaaaaa.net"
    key_name      = "aaaaaaa."
    key_algorithm = "hmac-md5"
    key_secret    = "bhifbiefjefg=="
  }
}

# Create a DNS NS record set
resource "dns_ns_record_set" "testingNS" {
    zone = "aaaaaaa"
    name = "pdx.cloud"
    nameservers = "testingns-385.awsdns-48.com."
    ttl = 300
}
 ```

Can someone please suggest what I might be doing wrong? 

Thank you

**Comment by apparentlymart** [comment]
Hi @anuiq! Thanks for working on this, and sorry things aren't working out so far.

Would it be possible for you to commit your changes and open a PR against this repository for them? That way it'll be easier to run the code you have and reproduce the error you're seeing to try to understand where it's coming from. It's totally fine to open a PR for work still in progress, and it'll make it easier to see the full context here.

Based on the error message, it looks like the error is coming from the Read function, in the `if r.Rcode != dns.RcodeSuccess` block. Looking at [the DNS response codes](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6) it looks like error 3, as mentioned in your error message here, is `NXDOMAIN`. This suggests that the new record just created doesn't exist on the DNS server that is being read. Is the `server` value in your `update` block pointing at a specific DNS server, or is it pointing to a pool of two or more servers? Is it possible that a change written to one server may not be immediately reflected on another?

**Comment by anuiq** [comment]
@apparentlymart Thank you for your response. I actually did try to create a PR however, I received a permission denied so forked it and pushed code into this repo: 

https://github.com/anuiq/terraform-provider-dns. 

Two scenarios are taking place 
1- When I dont add a '.' at the end of the zone name 

``` provider "dns" {
  update {
    server        = "las-abc.net"
    key_name      = "keyname"
    key_algorithm = "hmac-md5"
    key_secret    = "5fieufgefffbA64W="
  }
}

# Create a DNS NS record set
resource "dns_ns_record_set" "pdx.cloud" {
    zone = "zonename"
    name = "pdx.cloud
    nameservers = ""
    ttl = 300
}
```
Error : 

``` 
* dns_ns_record_set.testingns: 1 error(s) occurred:

* dns_ns_record_set.testingns: Error creating DNS record: "zone" should be an FQDN
```
2- When I add a '.' at the end 
``` provider "dns" {
  update {
    server        = "las-abc.net"
    key_name      = "keyname"
    key_algorithm = "hmac-md5"
    key_secret    = "5fieufgefffbA64W="
  }
}


# Create a DNS NS record set
resource "dns_ns_record_set" "pdx.cloud" {
    zone = "zonename."
    name = "pdx.cloud
    nameservers = ""
    ttl = 300
}
```

Error : 

``` 
Error refreshing state: 1 error(s) occurred:

* dns_ns_record_set.testingns: 1 error(s) occurred:

* dns_ns_record_set.testingns: dns_ns_record_set.testingns: Error querying DNS record: 3
```
I dont see these problems when I am trying to add A records BTW. The zone works very in that scenario. 

To answer your question 
Is the server value in your update block pointing at a specific DNS server, or is it pointing to a pool of two or more servers? -- My update block is pointing to a specific server. That server is reachable from the network I am in so that is ok I think. 

I am not quiet sure about the problem here. Any help would be appreciated.

**Comment by apparentlymart** [comment]
Hi again @anuiq!

It's normal that you would see a permission denied message when pushing to this repository, and so pushing the commit to your fork as you did is the right thing to do here. You should now be able to [open a pull request for your change](https://github.com/terraform-providers/terraform-provider-dns/compare/master...anuiq:master) if you'd like.

----

Looking more at this error... I'm not very experienced with dynamic DNS so I'm not sure what to suggest here but my next idea would be to try to reproduce the query that the Terraform provider is making with the `dig` command (or some other DNS client) and see if you get the same result. For example:

```
$ dig pdx.cloud.zonename. NS las-abc.net
```

or perhaps to try to enumerate the zone using a zone transfer, if the server is configured to allow this:

```
$ dig pdx.cloud.zonename. AXFR las-abc.net
```

If the above commands show that the NS record exists then that would suggest that it's the _reading_ part that's not working correctly, whereas if it _doesn't_ exist then perhaps the writing part is malfunctioning.

I'm going to see if I can get an environment set up here so I can try to reproduce your results. I don't have a writable DNS server handy to test, but this provider has a script for setting one up using docker in order to run the acceptance tests so I'm going to see if I can reproduce with that.

**Comment by apparentlymart** [comment]
I did some work on the acceptance tests you'd added for the NS resources and was able to reproduce the problem you've been seeing there.

I found a few problems along the way that I think partially explain this behavior:
* In a few different places the NS record resource code was calling into the A record resource code due to some missed updates, and so it trying to creating / reading A records instead of NS records in some places.
* The `resourceDnsNSRecordSetUpdate` function was still creating `A` records since the strings passed to `dns.NewRR` still had `A`, instead of `NS`.
* The `nameservers` attribute was defined as being `TypeString` rather than `TypeSet` of `TypeString`, so the code within the `d.HasChange("nameservers")` was panicking.

After addressing the above items the acceptance test failed in the same way as you saw in your own testing:

```
=== RUN   TestAccDnsNSRecordSet_Basic
--- FAIL: TestAccDnsNSRecordSet_Basic (0.11s)
	testing.go:435: Step 0 error: Error applying: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: Error querying DNS record: 3
	testing.go:499: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error refreshing: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: 1 error(s) occurred:
		
		* dns_ns_record_set.foo: dns_ns_record_set.foo: Error querying DNS record: 3
		
		State: <nil>
```

I've run out of time today so I can't investigate any further, but I've pushed up a commit that includes both your changes and mine which you can pull from here if you'd like to try my updates against your real server:

```
$ git checkout master
$ git pull --rebase
$ git checkout -b f-ns-records
$ git fetch https://github.com/terraform-providers/terraform-provider-dns anuiq-ns-record
$ git cherry-pick FETCH_HEAD
```

The above should leave you with a new branch `f-ns-records` in your local repository with both of our updates. 

I've put the diff between your original code and my updates here so you can see the full set of changes I made: https://gist.github.com/apparentlymart/aed4bcd27d615128071bde220aa3443e

**Comment by anuiq** [comment]
Thank you for your help @apparentlymart. 
I think the creation and retrieval of NS records work now. I have committed the changes in my fork. I wasn't able to commit to f-ns-records branch in the provider itself because of permissions but I would really appreciate it if you can tell me how I can open up a PR in the providers repo.

**Comment by anuiq** [comment]
PR opened in terraform-provider-DNS. The issue is resolved.
