### ISSUE TITLE
Reverse DNS Zone 

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-dns#91]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.8

This is a more of a question. Does this provider support creating the reverse lookup zones? Trying to use this provider to create a reverse-lookup-zone on windows . Any thoughts ?

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
